/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VanField: (typeof import('vant/es'))['Field'];
    VanPicker: (typeof import('vant/es'))['Picker'];
    VanPopup: (typeof import('vant/es'))['Popup'];
  }
}
